<?php

return [
    [
        'id' => 1,
        'title' => 'Serenity Lakeside Villa',
        'slug' => 'serenity-lakeside-villa',
        'location' => 'Pondok Indah, Jakarta Selatan',
        'city' => 'Jakarta',
        'type' => 'villa',
        'price' => 4800000000,
        'land_area' => 520,
        'building_area' => 450,
        'bedrooms' => 5,
        'bathrooms' => 4,
        'garages' => 2,
        'specs' => [
            'Private pool',
            'Garden lounge',
            'Smart home system',
            'Maid room',
            'Near Pondok Indah Mall',
        ],
        'keywords' => ['luxury', 'premium', 'south jakarta', 'family'],
        'description' => 'Premium lakeside villa with resort-style living, minutes from Pondok Indah Mall and international schools.',
        'image' => 'https://images.unsplash.com/photo-1600607687920-4e2a9b9cfe81?auto=format&fit=crop&w=1200&q=80',
    ],
    [
        'id' => 2,
        'title' => 'Urban Heights Apartment',
        'slug' => 'urban-heights-apartment',
        'location' => 'Sudirman, Jakarta Pusat',
        'city' => 'Jakarta',
        'type' => 'apartment',
        'price' => 1850000000,
        'land_area' => 0,
        'building_area' => 95,
        'bedrooms' => 2,
        'bathrooms' => 2,
        'garages' => 1,
        'specs' => [
            'City skyline view',
            'Infinity pool',
            'Co-working lounge',
            'Gym & sauna',
            '5 mins to MRT Setiabudi',
        ],
        'keywords' => ['city', 'investment', 'central business district', 'mrt'],
        'description' => 'Modern apartment in the heart of Sudirman CBD with complete facilities and direct MRT access.',
        'image' => 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&w=1200&q=80',
    ],
    [
        'id' => 3,
        'title' => 'Greenwood Family House',
        'slug' => 'greenwood-family-house',
        'location' => 'BSD City, Tangerang',
        'city' => 'Tangerang',
        'type' => 'house',
        'price' => 2350000000,
        'land_area' => 240,
        'building_area' => 210,
        'bedrooms' => 4,
        'bathrooms' => 3,
        'garages' => 2,
        'specs' => [
            'Corner unit',
            'Clubhouse access',
            'Kids playground',
            'Near AEON Mall',
            'Gated cluster',
        ],
        'keywords' => ['family', 'suburban', 'safe', 'playground'],
        'description' => 'Bright family home in BSD with green surroundings, clubhouse membership, and walking distance to schools.',
        'image' => 'https://images.unsplash.com/photo-1622015663319-b7f6f11f9d5f?auto=format&fit=crop&w=1200&q=80',
    ],
    [
        'id' => 4,
        'title' => 'Canggu Investment Land',
        'slug' => 'canggu-investment-land',
        'location' => 'Canggu, Bali',
        'city' => 'Badung',
        'type' => 'land',
        'price' => 950000000,
        'land_area' => 400,
        'building_area' => 0,
        'bedrooms' => 0,
        'bathrooms' => 0,
        'garages' => 0,
        'specs' => [
            'Tourist hotspot',
            'Main road access',
            '15 mins to Batu Bolong Beach',
            'Ready to build',
        ],
        'keywords' => ['land', 'bali', 'investment', 'tourism'],
        'description' => 'Strategic plot in booming Canggu area, ideal for villa complex or boutique hospitality development.',
        'image' => 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
    ],
    [
        'id' => 5,
        'title' => 'Central Business Loft',
        'slug' => 'central-business-loft',
        'location' => 'Kuningan, Jakarta Selatan',
        'city' => 'Jakarta',
        'type' => 'commercial',
        'price' => 3650000000,
        'land_area' => 180,
        'building_area' => 320,
        'bedrooms' => 0,
        'bathrooms' => 2,
        'garages' => 4,
        'specs' => [
            'Triple access',
            'High ceiling',
            'Dedicated meeting rooms',
            'Parking for 6 cars',
            'Fiber optic ready',
        ],
        'keywords' => ['office', 'workspace', 'kuningan', 'business'],
        'description' => 'Modern loft office in Kuningan CBD with ample parking and premium meeting facilities.',
        'image' => 'https://images.unsplash.com/photo-1560448075-bb485b067938?auto=format&fit=crop&w=1200&q=80',
    ],
    [
        'id' => 6,
        'title' => 'Sunrise Riverside House',
        'slug' => 'sunrise-riverside-house',
        'location' => 'Grand Galaxy City, Bekasi',
        'city' => 'Bekasi',
        'type' => 'house',
        'price' => 1450000000,
        'land_area' => 160,
        'building_area' => 150,
        'bedrooms' => 3,
        'bathrooms' => 3,
        'garages' => 1,
        'specs' => [
            'Riverside jogging track',
            'Renovated kitchen',
            'Solar water heater',
            'Nearby hospital',
            '24/7 security',
        ],
        'keywords' => ['affordable', 'renovated', 'river', 'security'],
        'description' => 'Comfortable riverside home with renovated interiors and close to lifestyle facilities in Grand Galaxy.',
        'image' => 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80',
    ],
    [
        'id' => 7,
        'title' => 'Mountain Breeze Villa',
        'slug' => 'mountain-breeze-villa',
        'location' => 'Lembang, Bandung',
        'city' => 'Bandung',
        'type' => 'villa',
        'price' => 2750000000,
        'land_area' => 600,
        'building_area' => 380,
        'bedrooms' => 4,
        'bathrooms' => 3,
        'garages' => 2,
        'specs' => [
            'Panoramic mountain view',
            'Fireplace lounge',
            'Outdoor deck',
            'Organic garden',
            'Fully furnished',
        ],
        'keywords' => ['villa', 'bandung', 'mountain', 'retreat'],
        'description' => 'Scenic villa in Lembang with cool weather, perfect for holiday home or exclusive guest house.',
        'image' => 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    ],
    [
        'id' => 8,
        'title' => 'Jaksel Creative Studio',
        'slug' => 'jaksel-creative-studio',
        'location' => 'Kemang, Jakarta Selatan',
        'city' => 'Jakarta',
        'type' => 'commercial',
        'price' => 2150000000,
        'land_area' => 150,
        'building_area' => 210,
        'bedrooms' => 1,
        'bathrooms' => 2,
        'garages' => 2,
        'specs' => [
            'Open-plan studio',
            'Acoustic treatment',
            'Coffee bar',
            'Walking distance to cafes',
            'Dual road access',
        ],
        'keywords' => ['creative', 'studio', 'kemang', 'cafe'],
        'description' => 'Flexible studio space in Kemang suited for agencies, creative hubs, or boutique showrooms.',
        'image' => 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?auto=format&fit=crop&w=1200&q=80',
    ],
];
